service: sls-devagram-auth

frameworkVersion: '3'

custom: 
  userPoolId: 'us-east-1_8EHXttmuc'
  userPoolClientId: 'CLIENTID'
  userTableName: 'users-table-${self:provider.stage}'
  avatarBucket: '${self:service}-${self:provider.stage}-avatars'
  apigwBinary:
    types:
      - 'multipart/form-data'
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'} 
  environment: 
    USER_POOL_ID: ${self:custom.userPoolId}
    USER_POOL_CLIENT_ID: ${self:custom.userPoolClientId}
    USER_TABLE: ${self:custom.userTableName}
    AVATAT_BUCKET: ${self:custom.avatarBucket}
  iam:
    role: 
      statements: 
        - Effect: Allow
          Action: 
            - dynamodb:*
          Resource:
            - "arn:aws:dynamodb:${self:provider.region}:*:table:${self:custom.userTableName}"

plugins:
  - serverless-plugin-typescript
  - serverless-apigw-binary

functions:
  signup:
    handler: src/functions/auth.register
    events:
      - http:
          path: register
          method: post
          cors: true
  confirmEmail:
    handler: src/functions/auth.confirmEmail
    events:
      - http:
          path: confirmEmail
          method: post
          cors: true
resources:
  Resources:
    CognitoUserPool: 
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:service}-${self:provider.stage}-user-pool
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: false
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        EmailVerificationMessage: "Seu código de verificação é {####}"
        EmailVerificationSubject: "Código de verificação Devagram"
        Policies: 
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
            RequireUppercase: true
    CognitoUserClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:service}-${self:provider.stage}-user-pool-client
        UserPoolId: !Ref CognitoUserPool         
        AllowedOAuthFlows:
          - implicit
        AllowedOAuthFlowsUserPoolClient: true
        AllowedOAuthScopes:
          - email
          - openid
        CallbackURLs:
          - https://www.devaria.com.br
        LogoutURLs:
          - https://www.devaria.com.br
        ExplicitAuthFlows:
          - ALLOW_CUSTOM_AUTH
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        SupportedIdentityProviders:
          - COGNITO
        ReadAttributes:
          - email
        WriteAttributes:
          - email
    CognitoUserDomain:
      Type: AWS::Cognito::UserPoolDomain
      Properties: 
        UserPoolId: !Ref CognitoUserPool
        Domain: ${self:service}-${self:provider.stage}-user-pool-domain-20221120-spinetti
    AvatarsBucket:
      Type: AWS::S3::Bucket
      Properties: 
        BucketName: ${self:custom.avatarBucket} 
        AccessControl: Private
    AvatarsBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties: 
        Bucket: !Ref AvatarsBucket
        PolicyDocument: 
          Statement:
            - Effect: Allow
              Principal: "*"
              Action: 
                - s3:PutObject
                - s3:GetObject
                - s3:DeleteObject
              Resource: 
                Fn::Join:
                  - ""
                  -
                    - "arn:aws:s3:::"
                    - !Ref AvatarsBucket
                    - "/*"